// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbljejuuujfjgpcxainn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpibGplanV1dWpmamdwY3hhaW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzMzNTcsImV4cCI6MjA1ODQwOTM1N30.e7uDilsJo8uKMWlk7ALP4o0X9sspogmyPQVxx8uzWY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);